<?php

use Illuminate\Database\Seeder;

class CampaignTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('psa_campaign')->insert([
            // for 1 brand
            [
                'id' => 1,
                'brand_id' => '68d87a0e-b72b-4721-bb04-50392bd105bd',
                'identity' => 'c26cc81f-9cff-44b2-bdca-66ecbf90145f',
                'status' => 'open',
                'type' => 'public',
                'visibility' => 'published',
                'disclosure' => '#sponsored',
                'title' => 'Warby Parker',
                'details' => 'details',
                'social_network' => 'Twitter',
                'submission_deadline' => '2016-06-23',
                'application_deadline' => '2016-06-08',
                'guidelines' => 'a:1:{i:0;a:1:{s:4:"text";s:19:"Хочу банан";}}',
                'media' => 'image',
                'compensation' => rand(20, 10000),
                'minimum_reach' => 1,
                'posting_date' => '2016-06-30',
                'condition' => 'project',
                'hashtag' => 'a:1:{i:0;s:5:"#coke";}',
                'mention' => 'a:1:{i:0;s:5:"@coke";}',
                'url' => 'www.cocacola.com',
                'campaign_image' => 'https://s3-us-west-2.amazonaws.com/sparkwoo-uploads/uploads/32fddee38dfe78d4821c8f8c416e6bf3.png',
            ],
            [
                'id' => 2,
                'brand_id' => '68d87a0e-b72b-4721-bb04-50392bd105bd',
                'identity' => 'fd37b8f1-efc2-4eab-8dbd-955a3a2be879',
                'status' => 'open',
                'type' => 'public',
                'visibility' => 'published',
                'disclosure' => '#sponsored',
                'title' => 'charity: water',
                'details' => 'details',
                'social_network' => 'Twitter',
                'submission_deadline' => '2016-06-23',
                'application_deadline' => '2016-06-08',
                'guidelines' => 'a:1:{i:0;a:1:{s:4:"text";s:19:"Хочу банан";}}',
                'media' => 'image',
                'compensation' => rand(20, 10000),
                'minimum_reach' => 1,
                'posting_date' => '2016-06-30',
                'condition' => 'project',
                'hashtag' => 'a:1:{i:0;s:5:"#coke";}',
                'mention' => 'a:1:{i:0;s:5:"@coke";}',
                'url' => 'www.cocacola.com',
                'campaign_image' => 'https://s3-us-west-2.amazonaws.com/sparkwoo-uploads/uploads/32fddee38dfe78d4821c8f8c416e6bf3.png',
            ],
            [
                'id' => 3,
                'brand_id' => '68d87a0e-b72b-4721-bb04-50392bd105bd',
                'identity' => 'a24ae881-b96d-407e-8333-0ea6fcd47a13',
                'status' => 'open',
                'type' => 'public',
                'visibility' => 'published',
                'disclosure' => '#sponsored',
                'title' => 'BuzzFeed',
                'details' => 'details',
                'social_network' => 'Twitter',
                'submission_deadline' => '2016-06-23',
                'application_deadline' => '2016-06-08',
                'guidelines' => 'a:1:{i:0;a:1:{s:4:"text";s:19:"Хочу банан";}}',
                'media' => 'image',
                'compensation' => rand(20, 10000),
                'minimum_reach' => 1,
                'posting_date' => '2016-06-30',
                'condition' => 'project',
                'hashtag' => 'a:1:{i:0;s:5:"#coke";}',
                'mention' => 'a:1:{i:0;s:5:"@coke";}',
                'url' => 'www.cocacola.com',
                'campaign_image' => 'https://s3-us-west-2.amazonaws.com/sparkwoo-uploads/uploads/32fddee38dfe78d4821c8f8c416e6bf3.png',
            ],
            [
                'id' => 4,
                'brand_id' => '68d87a0e-b72b-4721-bb04-50392bd105bd',
                'identity' => '3ceed78a-7268-4143-a786-19c61c83d08d',
                'status' => 'open',
                'type' => 'public',
                'visibility' => 'published',
                'disclosure' => '#sponsored',
                'title' => 'Canva',
                'details' => 'details',
                'social_network' => 'Twitter',
                'submission_deadline' => '2016-06-23',
                'application_deadline' => '2016-06-08',
                'guidelines' => 'a:1:{i:0;a:1:{s:4:"text";s:19:"Хочу банан";}}',
                'media' => 'image',
                'compensation' => rand(20, 10000),
                'minimum_reach' => 1,
                'posting_date' => '2016-06-30',
                'condition' => 'project',
                'hashtag' => 'a:1:{i:0;s:5:"#coke";}',
                'mention' => 'a:1:{i:0;s:5:"@coke";}',
                'url' => 'www.cocacola.com',
                'campaign_image' => 'https://s3-us-west-2.amazonaws.com/sparkwoo-uploads/uploads/32fddee38dfe78d4821c8f8c416e6bf3.png',
            ],
            [
                'id' => 5,
                'brand_id' => '68d87a0e-b72b-4721-bb04-50392bd105bd',
                'identity' => 'e4ff07f6-db1f-4b94-95c2-b6016dff4616',
                'status' => 'open',
                'type' => 'public',
                'visibility' => 'published',
                'disclosure' => '#sponsored',
                'title' => 'Birchbox',
                'details' => 'details',
                'social_network' => 'Twitter',
                'submission_deadline' => '2016-06-23',
                'application_deadline' => '2016-06-08',
                'guidelines' => 'a:1:{i:0;a:1:{s:4:"text";s:19:"Хочу банан";}}',
                'media' => 'image',
                'compensation' => rand(20, 10000),
                'minimum_reach' => 1,
                'posting_date' => '2016-06-30',
                'condition' => 'project',
                'hashtag' => 'a:1:{i:0;s:5:"#coke";}',
                'mention' => 'a:1:{i:0;s:5:"@coke";}',
                'url' => 'www.cocacola.com',
                'campaign_image' => 'https://s3-us-west-2.amazonaws.com/sparkwoo-uploads/uploads/32fddee38dfe78d4821c8f8c416e6bf3.png',
            ],
            // for 2 brand
            [
                'id' => 6,
                'brand_id' => 'd3232800-ef88-45fe-8bfb-dcc993401444',
                'identity' => '9c615ecc-72d8-4529-bfc2-a897b6aa6463',
                'status' => 'open',
                'type' => 'public',
                'visibility' => 'published',
                'disclosure' => '#sponsored',
                'title' => 'Cook Smarts',
                'details' => 'details',
                'social_network' => 'Twitter',
                'submission_deadline' => '2016-06-23',
                'application_deadline' => '2016-06-08',
                'guidelines' => 'a:1:{i:0;a:1:{s:4:"text";s:19:"Хочу банан";}}',
                'media' => 'image',
                'compensation' => rand(20, 10000),
                'minimum_reach' => 1,
                'posting_date' => '2016-06-30',
                'condition' => 'project',
                'hashtag' => 'a:1:{i:0;s:5:"#navi";}',
                'mention' => 'a:1:{i:0;s:5:"@navi";}',
                'url' => 'www.navi-gaming.com',
                'campaign_image' => 'http://s.navi-gaming.com/images/navi_logo_164_143.png',
            ],
            [
                'id' => 7,
                'brand_id' => 'd3232800-ef88-45fe-8bfb-dcc993401444',
                'identity' => '3e4557bf-bab8-412d-9fa4-0b6384f0005f',
                'status' => 'open',
                'type' => 'public',
                'visibility' => 'published',
                'disclosure' => '#sponsored',
                'title' => 'Dropbox',
                'details' => 'details',
                'social_network' => 'Twitter',
                'submission_deadline' => '2016-06-23',
                'application_deadline' => '2016-06-08',
                'guidelines' => 'a:1:{i:0;a:1:{s:4:"text";s:19:"Хочу банан";}}',
                'media' => 'image',
                'compensation' => rand(20, 10000),
                'minimum_reach' => 1,
                'posting_date' => '2016-06-30',
                'condition' => 'project',
                'hashtag' => 'a:1:{i:0;s:5:"#navi";}',
                'mention' => 'a:1:{i:0;s:5:"@navi";}',
                'url' => 'www.navi-gaming.com',
                'campaign_image' => 'http://s.navi-gaming.com/images/navi_logo_164_143.png',
            ],
            [
                'id' => 8,
                'brand_id' => 'd3232800-ef88-45fe-8bfb-dcc993401444',
                'identity' => '1bfdaf8f-52dc-4c90-afc0-f7271add5941',
                'status' => 'open',
                'type' => 'public',
                'visibility' => 'published',
                'disclosure' => '#sponsored',
                'title' => 'Paperless Post',
                'details' => 'details',
                'social_network' => 'Twitter',
                'submission_deadline' => '2016-06-23',
                'application_deadline' => '2016-06-08',
                'guidelines' => 'a:1:{i:0;a:1:{s:4:"text";s:19:"Хочу банан";}}',
                'media' => 'image',
                'compensation' => rand(20, 10000),
                'minimum_reach' => 1,
                'posting_date' => '2016-06-30',
                'condition' => 'project',
                'hashtag' => 'a:1:{i:0;s:5:"#navi";}',
                'mention' => 'a:1:{i:0;s:5:"@navi";}',
                'url' => 'www.navi-gaming.com',
                'campaign_image' => 'http://s.navi-gaming.com/images/navi_logo_164_143.png',
            ],
            [
                'id' => 9,
                'brand_id' => 'd3232800-ef88-45fe-8bfb-dcc993401444',
                'identity' => '47a2a0b8-31a8-4238-9c40-c001bf3ba5bf',
                'status' => 'open',
                'type' => 'public',
                'visibility' => 'published',
                'disclosure' => '#sponsored',
                'title' => 'Stitcher',
                'details' => 'details',
                'social_network' => 'Twitter',
                'submission_deadline' => '2016-06-23',
                'application_deadline' => '2016-06-08',
                'guidelines' => 'a:1:{i:0;a:1:{s:4:"text";s:19:"Хочу банан";}}',
                'media' => 'image',
                'compensation' => rand(20, 10000),
                'minimum_reach' => 1,
                'posting_date' => '2016-06-30',
                'condition' => 'project',
                'hashtag' => 'a:1:{i:0;s:5:"#navi";}',
                'mention' => 'a:1:{i:0;s:5:"@navi";}',
                'url' => 'www.navi-gaming.com',
                'campaign_image' => 'http://s.navi-gaming.com/images/navi_logo_164_143.png',
            ],
            [
                'id' => 10,
                'brand_id' => 'd3232800-ef88-45fe-8bfb-dcc993401444',
                'identity' => 'fea23d38-e517-4cea-ba5b-05845915d1ad',
                'status' => 'open',
                'type' => 'public',
                'visibility' => 'published',
                'disclosure' => '#sponsored',
                'title' => 'Turnstyle Cycle',
                'details' => 'details',
                'social_network' => 'Twitter',
                'submission_deadline' => '2016-06-23',
                'application_deadline' => '2016-06-08',
                'guidelines' => 'a:1:{i:0;a:1:{s:4:"text";s:19:"Хочу банан";}}',
                'media' => 'image',
                'compensation' => rand(20, 10000),
                'minimum_reach' => 1,
                'posting_date' => '2016-06-30',
                'condition' => 'project',
                'hashtag' => 'a:1:{i:0;s:5:"#navi";}',
                'mention' => 'a:1:{i:0;s:5:"@navi";}',
                'url' => 'www.navi-gaming.com',
                'campaign_image' => 'http://s.navi-gaming.com/images/navi_logo_164_143.png',
            ],
            // for 3 brand
            [
                'id' => 11,
                'brand_id' => 'fe04b80e-bf71-4928-929a-681d574f12ae',
                'identity' => '0c7b568f-1141-410f-ba92-40ebbe7df334',
                'status' => 'open',
                'type' => 'public',
                'visibility' => 'published',
                'disclosure' => '#sponsored',
                'title' => 'Poppin',
                'details' => 'details',
                'social_network' => 'Twitter',
                'submission_deadline' => '2016-06-23',
                'application_deadline' => '2016-06-08',
                'guidelines' => 'a:1:{i:0;a:1:{s:4:"text";s:19:"Хочу банан";}}',
                'media' => 'image',
                'compensation' => rand(20, 10000),
                'minimum_reach' => 1,
                'posting_date' => '2016-06-30',
                'condition' => 'project',
                'hashtag' => 'a:1:{i:0;s:9:"#McDonald";}',
                'mention' => 'a:1:{i:0;s:9:"@McDonald";}',
                'url' => 'www.aboutmcdonalds.com',
                'campaign_image' => 'http://www.aboutmcdonalds.com/etc/designs/aboutmcdonalds/jcr:content/genericpage/genericpagecontent/sitelevelconfiguration/logoimage.img.png',
            ],
            [
                'id' => 12,
                'brand_id' => 'fe04b80e-bf71-4928-929a-681d574f12ae',
                'identity' => '01f04272-991e-49e4-b47e-09bfbcb927da',
                'status' => 'open',
                'type' => 'public',
                'visibility' => 'published',
                'disclosure' => '#sponsored',
                'title' => 'Drybar',
                'details' => 'details',
                'social_network' => 'Twitter',
                'submission_deadline' => '2016-06-23',
                'application_deadline' => '2016-06-08',
                'guidelines' => 'a:1:{i:0;a:1:{s:4:"text";s:19:"Хочу банан";}}',
                'media' => 'image',
                'compensation' => rand(20, 10000),
                'minimum_reach' => 1,
                'posting_date' => '2016-06-30',
                'condition' => 'project',
                'hashtag' => 'a:1:{i:0;s:9:"#McDonald";}',
                'mention' => 'a:1:{i:0;s:9:"@McDonald";}',
                'url' => 'www.aboutmcdonalds.com',
                'campaign_image' => 'http://www.aboutmcdonalds.com/etc/designs/aboutmcdonalds/jcr:content/genericpage/genericpagecontent/sitelevelconfiguration/logoimage.img.png',
            ],
            [
                'id' => 13,
                'brand_id' => 'fe04b80e-bf71-4928-929a-681d574f12ae',
                'identity' => '27dca64a-ec7a-4435-bf82-6090c66eb39c',
                'status' => 'open',
                'type' => 'public',
                'visibility' => 'published',
                'disclosure' => '#sponsored',
                'title' => 'Google push',
                'details' => 'details',
                'social_network' => 'Twitter',
                'submission_deadline' => '2016-06-23',
                'application_deadline' => '2016-06-08',
                'guidelines' => 'a:1:{i:0;a:1:{s:4:"text";s:19:"Хочу банан";}}',
                'media' => 'image',
                'compensation' => rand(20, 10000),
                'minimum_reach' => 1,
                'posting_date' => '2016-06-30',
                'condition' => 'project',
                'hashtag' => 'a:1:{i:0;s:9:"#McDonald";}',
                'mention' => 'a:1:{i:0;s:9:"@McDonald";}',
                'url' => 'www.aboutmcdonalds.com',
                'campaign_image' => 'http://www.aboutmcdonalds.com/etc/designs/aboutmcdonalds/jcr:content/genericpage/genericpagecontent/sitelevelconfiguration/logoimage.img.png',
            ],
            [
                'id' => 14,
                'brand_id' => 'fe04b80e-bf71-4928-929a-681d574f12ae',
                'identity' => 'a9bb4b42-24aa-4530-b771-eb296194bd12',
                'status' => 'open',
                'type' => 'public',
                'visibility' => 'published',
                'disclosure' => '#sponsored',
                'title' => 'Composer is best',
                'details' => 'details',
                'social_network' => 'Twitter',
                'submission_deadline' => '2016-06-23',
                'application_deadline' => '2016-06-08',
                'guidelines' => 'a:1:{i:0;a:1:{s:4:"text";s:19:"Хочу банан";}}',
                'media' => 'image',
                'compensation' => rand(20, 10000),
                'minimum_reach' => 1,
                'posting_date' => '2016-06-30',
                'condition' => 'project',
                'hashtag' => 'a:1:{i:0;s:9:"#McDonald";}',
                'mention' => 'a:1:{i:0;s:9:"@McDonald";}',
                'url' => 'www.aboutmcdonalds.com',
                'campaign_image' => 'http://www.aboutmcdonalds.com/etc/designs/aboutmcdonalds/jcr:content/genericpage/genericpagecontent/sitelevelconfiguration/logoimage.img.png',
            ],
            [
                'id' => 15,
                'brand_id' => 'fe04b80e-bf71-4928-929a-681d574f12ae',
                'identity' => 'e41d2d39-a835-417b-9678-adfb9f4c5ed7',
                'status' => 'open',
                'type' => 'private',
                'visibility' => 'published',
                'disclosure' => '#sponsored',
                'title' => 'Git is everyday thins',
                'details' => 'details',
                'social_network' => 'Twitter',
                'submission_deadline' => '2016-06-23',
                'application_deadline' => '2016-06-08',
                'guidelines' => 'a:1:{i:0;a:1:{s:4:"text";s:19:"Хочу банан";}}',
                'media' => 'image',
                'compensation' => rand(20, 10000),
                'minimum_reach' => 1,
                'posting_date' => '2016-06-30',
                'condition' => 'project',
                'hashtag' => 'a:1:{i:0;s:9:"#McDonald";}',
                'mention' => 'a:1:{i:0;s:9:"@McDonald";}',
                'url' => 'www.aboutmcdonalds.com',
                'campaign_image' => 'http://www.aboutmcdonalds.com/etc/designs/aboutmcdonalds/jcr:content/genericpage/genericpagecontent/sitelevelconfiguration/logoimage.img.png',
            ],
        ]);
    }
}
