<?php

use Illuminate\Database\Seeder;

class InfluencersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('psa_influencers')->insert([
            [
                'id' => 7,
                'email' => 'influencer_1@sparkwoo.com',
                'first_name' => 'Trace',
                'last_name' => 'Adkins',
                'gender' => 'Male',
                'age' => rand(20, 60),
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Trace_Adkins_on_stage.jpg/220px-Trace_Adkins_on_stage.jpg',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Trace_Adkins_on_stage.jpg/220px-Trace_Adkins_on_stage.jpg',
                'location_state' => 'Arizona',
            ],
            [
                'id' => 8,
                'email' => 'influencer_2@sparkwoo.com',
                'first_name' => 'Bo',
                'last_name' => 'Bice',
                'gender' => 'Male',
                'age' => rand(20, 60),
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Bo_Bice.jpg/220px-Bo_Bice.jpg',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Bo_Bice.jpg/220px-Bo_Bice.jpg',
                'location_state' => 'Alabama',
            ],
            [
                'id' => 9,
                'email' => 'influencer_3@sparkwoo.com',
                'first_name' => 'Jesse',
                'last_name' => 'Brand',
                'gender' => 'Male',
                'age' => rand(20, 60),
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Jesse_Brand_Live_At_The_2014_Texas_music_Awards.jpeg/220px-Jesse_Brand_Live_At_The_2014_Texas_music_Awards.jpeg',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Jesse_Brand_Live_At_The_2014_Texas_music_Awards.jpeg/220px-Jesse_Brand_Live_At_The_2014_Texas_music_Awards.jpeg',
                'location_state' => 'Arizona',
            ],
            [
                'id' => 10,
                'email' => 'influencer_4@sparkwoo.com',
                'first_name' => 'Jimmy',
                'last_name' => 'Buffett',
                'gender' => 'Male',
                'age' => rand(20, 60),
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Jimmy_Buffett_1.jpg/220px-Jimmy_Buffett_1.jpg',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Jimmy_Buffett_1.jpg/220px-Jimmy_Buffett_1.jpg',
                'location_state' => 'Arizona',
            ],
            [
                'id' => 11,
                'email' => 'influencer_5@sparkwoo.com',
                'first_name' => 'Eric',
                'last_name' => 'Adams',
                'gender' => 'Male',
                'age' => rand(20, 60),
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/2002.11.18_manowar_bercy_eric_adams_1.jpg/800px-2002.11.18_manowar_bercy_eric_adams_1.jpg',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/2002.11.18_manowar_bercy_eric_adams_1.jpg/800px-2002.11.18_manowar_bercy_eric_adams_1.jpg',
                'location_state' => 'Arizona',
            ],
            [
                'id' => 12,
                'email' => 'influencer_6@sparkwoo.com',
                'first_name' => 'Ray',
                'last_name' => 'Alder',
                'gender' => 'Male',
                'age' => rand(20, 60),
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/c/c2/Alder_2007.jpg',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/c/c2/Alder_2007.jpg',
                'location_state' => 'Arizona',
            ],
            [
                'id' => 13,
                'email' => 'influencer_7@sparkwoo.com',
                'first_name' => 'Carson',
                'last_name' => 'Allen',
                'gender' => 'Male',
                'age' => rand(20, 60),
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Carson_Allen.jpg/220px-Carson_Allen.jpg',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Carson_Allen.jpg/220px-Carson_Allen.jpg',
                'location_state' => 'Arizona',
            ],
            [
                'id' => 14,
                'email' => 'influencer_8@sparkwoo.com',
                'first_name' => 'Russell',
                'last_name' => 'Allen',
                'gender' => 'Male',
                'age' => rand(20, 60),
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Symphony_x_10.jpg/220px-Symphony_x_10.jpg',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Symphony_x_10.jpg/220px-Symphony_x_10.jpg',
                'location_state' => 'Arizona',
            ],
            [
                'id' => 15,
                'email' => 'influencer_9@sparkwoo.com',
                'first_name' => 'Jared',
                'last_name' => 'Anderson',
                'gender' => 'Male',
                'age' => rand(20, 60),
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Jared_Anderson.jpg/400px-Jared_Anderson.jpg',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Jared_Anderson.jpg/400px-Jared_Anderson.jpg',
                'location_state' => 'Arizona',
            ],
            [
                'id' => 16,
                'email' => 'influencer_10@sparkwoo.com',
                'first_name' => 'Phil',
                'last_name' => 'Anselmo',
                'gender' => 'Male',
                'age' => rand(20, 60),
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Down_07.jpg/280px-Down_07.jpg',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Down_07.jpg/280px-Down_07.jpg',
                'location_state' => 'Arizona',
            ],
            [
                'id' => 17,
                'email' => 'influencer_11@sparkwoo.com',
                'first_name' => 'Tom',
                'last_name' => 'Araya',
                'gender' => 'Male',
                'age' => rand(20, 60),
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Slayer_-_Tom_Araya.jpg/250px-Slayer_-_Tom_Araya.jpg',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Slayer_-_Tom_Araya.jpg/250px-Slayer_-_Tom_Araya.jpg',
                'location_state' => 'Arizona',
            ],
            [
                'id' => 18,
                'email' => 'influencer_12@sparkwoo.com',
                'first_name' => 'Paul',
                'last_name' => 'Baloff',
                'gender' => 'Male',
                'age' => rand(20, 60),
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/7/7c/Paul_Baloff.jpg',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/7/7c/Paul_Baloff.jpg',
                'location_state' => 'Arizona',
            ],
            [
                'id' => 19,
                'email' => 'influencer_13@sparkwoo.com',
                'first_name' => 'Jacob',
                'last_name' => 'Bannon',
                'gender' => 'Male',
                'age' => rand(20, 60),
                'image' => 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Jacob_Bannon_in_performance_%28Paris%2C_2008%29.jpg/300px-Jacob_Bannon_in_performance_%28Paris%2C_2008%29.jpg',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Jacob_Bannon_in_performance_%28Paris%2C_2008%29.jpg/300px-Jacob_Bannon_in_performance_%28Paris%2C_2008%29.jpg',
                'location_state' => 'Arizona',
            ],
            [
                'id' => 20,
                'email' => 'influencer_14@sparkwoo.com',
                'first_name' => 'Matt',
                'last_name' => 'Barlow',
                'gender' => 'Male',
                'age' => rand(20, 60),
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/MattBarlow2010.jpg/300px-MattBarlow2010.jpg',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/MattBarlow2010.jpg/300px-MattBarlow2010.jpg',
                'location_state' => 'Arizona',
            ],
            [
                'id' => 21,
                'email' => 'influencer_15@sparkwoo.com',
                'first_name' => 'Chris',
                'last_name' => 'Barnes',
                'gender' => 'Male',
                'age' => rand(20, 60),
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Chris_Barnes.jpg/245px-Chris_Barnes.jpg',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Chris_Barnes.jpg/245px-Chris_Barnes.jpg',
                'location_state' => 'Arizona',
            ],
            [
                'id' => 22,
                'email' => 'influencer_16@sparkwoo.com',
                'first_name' => 'William',
                'last_name' => 'DuVall',
                'gender' => 'Male',
                'age' => rand(20, 60),
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/William_DuVall_-_Alice_in_Chains_-_Roskilde_Festival_2010.jpg/220px-William_DuVall_-_Alice_in_Chains_-_Roskilde_Festival_2010.jpg',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/William_DuVall_-_Alice_in_Chains_-_Roskilde_Festival_2010.jpg/220px-William_DuVall_-_Alice_in_Chains_-_Roskilde_Festival_2010.jpg',
                'location_state' => 'Arizona',
            ],
            [
                'id' => 23,
                'email' => 'influencer_17@sparkwoo.com',
                'first_name' => 'Matt',
                'last_name' => 'Fallon',
                'gender' => 'Male',
                'age' => rand(20, 60),
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/3/3f/Matt_Fallon_3.jpg',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/3/3f/Matt_Fallon_3.jpg',
                'location_state' => 'Arizona',
            ],
            [
                'id' => 24,
                'email' => 'influencer_18@sparkwoo.com',
                'first_name' => 'Chris',
                'last_name' => 'Fehn',
                'gender' => 'Male',
                'age' => rand(20, 60),
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Chris_Fehn.jpg/220px-Chris_Fehn.jpg',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Chris_Fehn.jpg/220px-Chris_Fehn.jpg',
                'location_state' => 'Arizona',
            ],
            [
                'id' => 25,
                'email' => 'influencer_19@sparkwoo.com',
                'first_name' => 'Lance',
                'last_name' => 'King',
                'gender' => 'Male',
                'age' => rand(20, 60),
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Vocalist_Lance_King_%40ProgPowerUSA_Sept.2007.jpg/220px-Vocalist_Lance_King_%40ProgPowerUSA_Sept.2007.jpg',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Vocalist_Lance_King_%40ProgPowerUSA_Sept.2007.jpg/220px-Vocalist_Lance_King_%40ProgPowerUSA_Sept.2007.jpg',
                'location_state' => 'Arizona',
            ],
            [
                'id' => 26,
                'email' => 'influencer_20@sparkwoo.com',
                'first_name' => 'Bobby',
                'last_name' => 'Ellsworth',
                'gender' => 'Male',
                'age' => rand(20, 60),
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Overkill_-_Jalometalli_2008_-_02.JPG/220px-Overkill_-_Jalometalli_2008_-_02.JPG',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Overkill_-_Jalometalli_2008_-_02.JPG/220px-Overkill_-_Jalometalli_2008_-_02.JPG',
                'location_state' => 'Arizona',
            ]
        ]);
    }
}
